-- 006a_seed_schools_part1.sql
-- Ivy League, Big Ten, SEC, ACC, Big 12, Pac-12, state flagships (A-M)
-- ~200 institutions. Run before 006b and 006c.

INSERT INTO public.schools (name, city, state) VALUES
-- ── Ivy League ──────────────────────────────────────────────────────────────
('Harvard University', 'Cambridge', 'MA'),
('Yale University', 'New Haven', 'CT'),
('Princeton University', 'Princeton', 'NJ'),
('Columbia University', 'New York', 'NY'),
('University of Pennsylvania', 'Philadelphia', 'PA'),
('Brown University', 'Providence', 'RI'),
('Dartmouth College', 'Hanover', 'NH'),
('Cornell University', 'Ithaca', 'NY'),

-- ── Big Ten ──────────────────────────────────────────────────────────────────
('University of Michigan', 'Ann Arbor', 'MI'),
('Michigan State University', 'East Lansing', 'MI'),
('Ohio State University', 'Columbus', 'OH'),
('Penn State University', 'University Park', 'PA'),
('University of Wisconsin-Madison', 'Madison', 'WI'),
('University of Minnesota Twin Cities', 'Minneapolis', 'MN'),
('University of Illinois Urbana-Champaign', 'Champaign', 'IL'),
('Northwestern University', 'Evanston', 'IL'),
('Purdue University', 'West Lafayette', 'IN'),
('Indiana University Bloomington', 'Bloomington', 'IN'),
('University of Iowa', 'Iowa City', 'IA'),
('University of Nebraska-Lincoln', 'Lincoln', 'NE'),
('Rutgers University', 'New Brunswick', 'NJ'),
('University of Maryland College Park', 'College Park', 'MD'),
('University of Washington', 'Seattle', 'WA'),
('UCLA', 'Los Angeles', 'CA'),
('USC', 'Los Angeles', 'CA'),
('UC Berkeley', 'Berkeley', 'CA'),
('University of Oregon', 'Eugene', 'OR'),
('Oregon State University', 'Corvallis', 'OR'),

-- ── SEC ──────────────────────────────────────────────────────────────────────
('University of Alabama', 'Tuscaloosa', 'AL'),
('Auburn University', 'Auburn', 'AL'),
('University of Arkansas', 'Fayetteville', 'AR'),
('University of Florida', 'Gainesville', 'FL'),
('University of Georgia', 'Athens', 'GA'),
('University of Kentucky', 'Lexington', 'KY'),
('Louisiana State University', 'Baton Rouge', 'LA'),
('University of Mississippi', 'Oxford', 'MS'),
('Mississippi State University', 'Starkville', 'MS'),
('University of Missouri', 'Columbia', 'MO'),
('University of South Carolina', 'Columbia', 'SC'),
('University of Tennessee', 'Knoxville', 'TN'),
('Texas A&M University', 'College Station', 'TX'),
('Vanderbilt University', 'Nashville', 'TN'),
('University of Texas at Austin', 'Austin', 'TX'),
('Oklahoma State University', 'Stillwater', 'OK'),

-- ── ACC ──────────────────────────────────────────────────────────────────────
('Duke University', 'Durham', 'NC'),
('University of North Carolina at Chapel Hill', 'Chapel Hill', 'NC'),
('NC State University', 'Raleigh', 'NC'),
('Wake Forest University', 'Winston-Salem', 'NC'),
('Georgia Tech', 'Atlanta', 'GA'),
('Clemson University', 'Clemson', 'SC'),
('Florida State University', 'Tallahassee', 'FL'),
('University of Miami', 'Coral Gables', 'FL'),
('University of Pittsburgh', 'Pittsburgh', 'PA'),
('Boston College', 'Chestnut Hill', 'MA'),
('Syracuse University', 'Syracuse', 'NY'),
('University of Virginia', 'Charlottesville', 'VA'),
('Virginia Tech', 'Blacksburg', 'VA'),
('University of Louisville', 'Louisville', 'KY'),
('Notre Dame', 'Notre Dame', 'IN'),
('Stanford University', 'Stanford', 'CA'),
('California', 'Berkeley', 'CA'),
('SMU', 'Dallas', 'TX'),
('Stanford', 'Stanford', 'CA'),

-- ── Big 12 ───────────────────────────────────────────────────────────────────
('University of Kansas', 'Lawrence', 'KS'),
('Kansas State University', 'Manhattan', 'KS'),
('Iowa State University', 'Ames', 'IA'),
('Baylor University', 'Waco', 'TX'),
('Texas Christian University', 'Fort Worth', 'TX'),
('Texas Tech University', 'Lubbock', 'TX'),
('University of Oklahoma', 'Norman', 'OK'),
('West Virginia University', 'Morgantown', 'WV'),
('University of Utah', 'Salt Lake City', 'UT'),
('Utah State University', 'Logan', 'UT'),
('Brigham Young University', 'Provo', 'UT'),
('University of Arizona', 'Tucson', 'AZ'),
('Arizona State University', 'Tempe', 'AZ'),
('University of Colorado Boulder', 'Boulder', 'CO'),
('Colorado State University', 'Fort Collins', 'CO'),
('University of Cincinnati', 'Cincinnati', 'OH'),
('University of Houston', 'Houston', 'TX'),
('University of Central Florida', 'Orlando', 'FL'),

-- ── Major private research universities ─────────────────────────────────────
('Massachusetts Institute of Technology', 'Cambridge', 'MA'),
('California Institute of Technology', 'Pasadena', 'CA'),
('University of Chicago', 'Chicago', 'IL'),
('Johns Hopkins University', 'Baltimore', 'MD'),
('Duke University', 'Durham', 'NC'),
('Rice University', 'Houston', 'TX'),
('Emory University', 'Atlanta', 'GA'),
('Washington University in St. Louis', 'St. Louis', 'MO'),
('Georgetown University', 'Washington', 'DC'),
('Tulane University', 'New Orleans', 'LA'),
('Tufts University', 'Medford', 'MA'),
('Carnegie Mellon University', 'Pittsburgh', 'PA'),
('New York University', 'New York', 'NY'),
('Boston University', 'Boston', 'MA'),
('Northeastern University', 'Boston', 'MA'),
('George Washington University', 'Washington', 'DC'),
('American University', 'Washington', 'DC'),
('Case Western Reserve University', 'Cleveland', 'OH'),
('Drexel University', 'Philadelphia', 'PA'),
('Fordham University', 'Bronx', 'NY'),
('Lehigh University', 'Bethlehem', 'PA'),
('Marquette University', 'Milwaukee', 'WI'),
('Rensselaer Polytechnic Institute', 'Troy', 'NY'),
('Rochester Institute of Technology', 'Rochester', 'NY'),
('Stevens Institute of Technology', 'Hoboken', 'NJ'),
('Villanova University', 'Villanova', 'PA'),
('Wake Forest University', 'Winston-Salem', 'NC'),
('Worcester Polytechnic Institute', 'Worcester', 'MA'),
('Loyola University Chicago', 'Chicago', 'IL'),
('DePaul University', 'Chicago', 'IL'),

-- ── State flagship universities (A–M) ────────────────────────────────────────
('University of Alaska Fairbanks', 'Fairbanks', 'AK'),
('University of Alaska Anchorage', 'Anchorage', 'AK'),
('University of Alabama at Birmingham', 'Birmingham', 'AL'),
('University of Arizona', 'Tucson', 'AZ'),
('University of Arkansas', 'Fayetteville', 'AR'),
('University of California Davis', 'Davis', 'CA'),
('UC San Diego', 'La Jolla', 'CA'),
('UC Santa Barbara', 'Santa Barbara', 'CA'),
('UC Irvine', 'Irvine', 'CA'),
('UC Santa Cruz', 'Santa Cruz', 'CA'),
('UC Riverside', 'Riverside', 'CA'),
('University of Denver', 'Denver', 'CO'),
('University of Connecticut', 'Storrs', 'CT'),
('University of Delaware', 'Newark', 'DE'),
('Florida International University', 'Miami', 'FL'),
('University of South Florida', 'Tampa', 'FL'),
('University of Hawaii at Manoa', 'Honolulu', 'HI'),
('Boise State University', 'Boise', 'ID'),
('University of Idaho', 'Moscow', 'ID'),
('Southern Illinois University Carbondale', 'Carbondale', 'IL'),
('University of Illinois Chicago', 'Chicago', 'IL'),
('University of Notre Dame', 'Notre Dame', 'IN'),
('University of Kansas', 'Lawrence', 'KS'),
('University of Louisiana Lafayette', 'Lafayette', 'LA'),
('University of Maine', 'Orono', 'ME'),
('University of Maryland Baltimore County', 'Baltimore', 'MD'),
('University of Massachusetts Amherst', 'Amherst', 'MA'),
('University of Massachusetts Boston', 'Boston', 'MA'),
('Michigan Technological University', 'Houghton', 'MI'),
('University of Minnesota Duluth', 'Duluth', 'MN'),
('University of Southern Mississippi', 'Hattiesburg', 'MS'),
('University of Montana', 'Missoula', 'MT')

ON CONFLICT (name) DO NOTHING;
