-- 006b_seed_schools_part2.sql
-- State flagships (N-W), liberal arts colleges, HBCUs, regional universities
-- ~200 more institutions.

INSERT INTO public.schools (name, city, state) VALUES
-- ── State flagships (N–W) ─────────────────────────────────────────────────────
('University of Nevada Las Vegas', 'Las Vegas', 'NV'),
('University of Nevada Reno', 'Reno', 'NV'),
('University of New Hampshire', 'Durham', 'NH'),
('Rutgers University-Newark', 'Newark', 'NJ'),
('New Jersey Institute of Technology', 'Newark', 'NJ'),
('University of New Mexico', 'Albuquerque', 'NM'),
('New Mexico State University', 'Las Cruces', 'NM'),
('State University of New York at Buffalo', 'Buffalo', 'NY'),
('Stony Brook University', 'Stony Brook', 'NY'),
('University at Albany', 'Albany', 'NY'),
('Binghamton University', 'Binghamton', 'NY'),
('North Carolina A&T State University', 'Greensboro', 'NC'),
('University of North Carolina Charlotte', 'Charlotte', 'NC'),
('University of North Carolina Greensboro', 'Greensboro', 'NC'),
('University of North Dakota', 'Grand Forks', 'ND'),
('North Dakota State University', 'Fargo', 'ND'),
('University of Akron', 'Akron', 'OH'),
('Bowling Green State University', 'Bowling Green', 'OH'),
('Cleveland State University', 'Cleveland', 'OH'),
('Kent State University', 'Kent', 'OH'),
('Miami University', 'Oxford', 'OH'),
('Ohio University', 'Athens', 'OH'),
('University of Toledo', 'Toledo', 'OH'),
('Wright State University', 'Dayton', 'OH'),
('University of Oklahoma', 'Norman', 'OK'),
('University of Oregon', 'Eugene', 'OR'),
('Portland State University', 'Portland', 'OR'),
('Temple University', 'Philadelphia', 'PA'),
('University of Rhode Island', 'Kingston', 'RI'),
('Clemson University', 'Clemson', 'SC'),
('South Carolina State University', 'Orangeburg', 'SC'),
('University of South Dakota', 'Vermillion', 'SD'),
('South Dakota State University', 'Brookings', 'SD'),
('Middle Tennessee State University', 'Murfreesboro', 'TN'),
('Tennessee State University', 'Nashville', 'TN'),
('University of Texas at Dallas', 'Richardson', 'TX'),
('University of Texas at El Paso', 'El Paso', 'TX'),
('University of Texas at San Antonio', 'San Antonio', 'TX'),
('University of Texas at Arlington', 'Arlington', 'TX'),
('University of Vermont', 'Burlington', 'VT'),
('University of Virginia', 'Charlottesville', 'VA'),
('Virginia Commonwealth University', 'Richmond', 'VA'),
('George Mason University', 'Fairfax', 'VA'),
('Old Dominion University', 'Norfolk', 'VA'),
('University of Washington Tacoma', 'Tacoma', 'WA'),
('Washington State University', 'Pullman', 'WA'),
('West Virginia University', 'Morgantown', 'WV'),
('University of Wisconsin Milwaukee', 'Milwaukee', 'WI'),
('University of Wisconsin Green Bay', 'Green Bay', 'WI'),
('University of Wyoming', 'Laramie', 'WY'),

-- ── Top liberal arts colleges ─────────────────────────────────────────────────
('Williams College', 'Williamstown', 'MA'),
('Amherst College', 'Amherst', 'MA'),
('Swarthmore College', 'Swarthmore', 'PA'),
('Wellesley College', 'Wellesley', 'MA'),
('Carleton College', 'Northfield', 'MN'),
('Pomona College', 'Claremont', 'CA'),
('Middlebury College', 'Middlebury', 'VT'),
('Bowdoin College', 'Brunswick', 'ME'),
('Grinnell College', 'Grinnell', 'IA'),
('Claremont McKenna College', 'Claremont', 'CA'),
('Davidson College', 'Davidson', 'NC'),
('Harvey Mudd College', 'Claremont', 'CA'),
('Haverford College', 'Haverford', 'PA'),
('Smith College', 'Northampton', 'MA'),
('Vassar College', 'Poughkeepsie', 'NY'),
('Colgate University', 'Hamilton', 'NY'),
('Hamilton College', 'Clinton', 'NY'),
('Colby College', 'Waterville', 'ME'),
('Bates College', 'Lewiston', 'ME'),
('Trinity College', 'Hartford', 'CT'),
('Wesleyan University', 'Middletown', 'CT'),
('Connecticut College', 'New London', 'CT'),
('Bryn Mawr College', 'Bryn Mawr', 'PA'),
('Oberlin College', 'Oberlin', 'OH'),
('Colorado College', 'Colorado Springs', 'CO'),
('Reed College', 'Portland', 'OR'),
('Whitman College', 'Walla Walla', 'WA'),
('Macalester College', 'St. Paul', 'MN'),
('Kenyon College', 'Gambier', 'OH'),
('Denison University', 'Granville', 'OH'),
('Furman University', 'Greenville', 'SC'),
('Rhodes College', 'Memphis', 'TN'),
('Sewanee: The University of the South', 'Sewanee', 'TN'),
('Wabash College', 'Crawfordsville', 'IN'),
('DePauw University', 'Greencastle', 'IN'),
('Earlham College', 'Richmond', 'IN'),
('Lawrence University', 'Appleton', 'WI'),
('Beloit College', 'Beloit', 'WI'),
('St. Olaf College', 'Northfield', 'MN'),
('Gustavus Adolphus College', 'St. Peter', 'MN'),

-- ── HBCUs ────────────────────────────────────────────────────────────────────
('Howard University', 'Washington', 'DC'),
('Spelman College', 'Atlanta', 'GA'),
('Morehouse College', 'Atlanta', 'GA'),
('Hampton University', 'Hampton', 'VA'),
('Xavier University of Louisiana', 'New Orleans', 'LA'),
('Fisk University', 'Nashville', 'TN'),
('Tuskegee University', 'Tuskegee', 'AL'),
('Morgan State University', 'Baltimore', 'MD'),
('Jackson State University', 'Jackson', 'MS'),
('Alcorn State University', 'Lorman', 'MS'),
('Prairie View A&M University', 'Prairie View', 'TX'),
('Texas Southern University', 'Houston', 'TX'),
('Florida A&M University', 'Tallahassee', 'FL'),
('Bethune-Cookman University', 'Daytona Beach', 'FL'),
('Clark Atlanta University', 'Atlanta', 'GA'),
('Morehouse School of Medicine', 'Atlanta', 'GA'),
('Meharry Medical College', 'Nashville', 'TN'),
('Delaware State University', 'Dover', 'DE'),
('Bowie State University', 'Bowie', 'MD'),
('Coppin State University', 'Baltimore', 'MD'),
('University of Maryland Eastern Shore', 'Princess Anne', 'MD'),
('Lincoln University', 'Lincoln University', 'PA'),
('Cheyney University', 'Cheyney', 'PA'),
('Norfolk State University', 'Norfolk', 'VA'),
('Virginia State University', 'Petersburg', 'VA'),
('Elizabeth City State University', 'Elizabeth City', 'NC'),
('Fayetteville State University', 'Fayetteville', 'NC'),
('Winston-Salem State University', 'Winston-Salem', 'NC'),
('North Carolina Central University', 'Durham', 'NC'),
('Grambling State University', 'Grambling', 'LA'),
('Southern University Baton Rouge', 'Baton Rouge', 'LA'),
('Dillard University', 'New Orleans', 'LA'),
('Wiley College', 'Marshall', 'TX'),
('Langston University', 'Langston', 'OK'),
('Tougaloo College', 'Tougaloo', 'MS'),
('Benedict College', 'Columbia', 'SC'),
('South Carolina State University', 'Orangeburg', 'SC'),
('Claflin University', 'Orangeburg', 'SC'),
('Alabama A&M University', 'Normal', 'AL'),
('Alabama State University', 'Montgomery', 'AL'),
('Stillman College', 'Tuscaloosa', 'AL'),
('Miles College', 'Birmingham', 'AL'),
('Talladega College', 'Talladega', 'AL'),
('LeMoyne-Owen College', 'Memphis', 'TN'),
('Lane College', 'Jackson', 'TN'),
('Tennessee State University', 'Nashville', 'TN'),
('Knoxville College', 'Knoxville', 'TN'),
('Kentucky State University', 'Frankfort', 'KY'),
('Central State University', 'Wilberforce', 'OH'),
('Lincoln University of Missouri', 'Jefferson City', 'MO'),

-- ── Regional comprehensive universities ──────────────────────────────────────
('Appalachian State University', 'Boone', 'NC'),
('Austin Peay State University', 'Clarksville', 'TN'),
('California State University Fullerton', 'Fullerton', 'CA'),
('California State University Long Beach', 'Long Beach', 'CA'),
('California State University Los Angeles', 'Los Angeles', 'CA'),
('California State University Northridge', 'Northridge', 'CA'),
('California State University Sacramento', 'Sacramento', 'CA'),
('California State University San Bernardino', 'San Bernardino', 'CA'),
('California Polytechnic State University San Luis Obispo', 'San Luis Obispo', 'CA'),
('California Polytechnic State University Pomona', 'Pomona', 'CA'),
('San Diego State University', 'San Diego', 'CA'),
('San Jose State University', 'San Jose', 'CA'),
('San Francisco State University', 'San Francisco', 'CA'),
('East Carolina University', 'Greenville', 'NC'),
('Eastern Illinois University', 'Charleston', 'IL'),
('Eastern Kentucky University', 'Richmond', 'KY'),
('Eastern Michigan University', 'Ypsilanti', 'MI'),
('Eastern Washington University', 'Cheney', 'WA'),
('Embry-Riddle Aeronautical University', 'Daytona Beach', 'FL'),
('Fairfield University', 'Fairfield', 'CT'),
('Florida Atlantic University', 'Boca Raton', 'FL'),
('Georgia Southern University', 'Statesboro', 'GA'),
('Georgia State University', 'Atlanta', 'GA'),
('Grand Valley State University', 'Allendale', 'MI')

ON CONFLICT (name) DO NOTHING;
