-- 006c_seed_schools_part3.sql
-- Additional regional, faith-based, technical, women's, and specialty schools
-- ~200 more institutions.

INSERT INTO public.schools (name, city, state) VALUES
-- ── More regional universities ────────────────────────────────────────────────
('Illinois State University', 'Normal', 'IL'),
('James Madison University', 'Harrisonburg', 'VA'),
('Kansas State University', 'Manhattan', 'KS'),
('Kennesaw State University', 'Kennesaw', 'GA'),
('Lamar University', 'Beaumont', 'TX'),
('Long Island University', 'Brooklyn', 'NY'),
('Marist College', 'Poughkeepsie', 'NY'),
('Mercer University', 'Macon', 'GA'),
('Minnesota State University Mankato', 'Mankato', 'MN'),
('Missouri State University', 'Springfield', 'MO'),
('Montana State University', 'Bozeman', 'MT'),
('Murray State University', 'Murray', 'KY'),
('New Mexico Tech', 'Socorro', 'NM'),
('Nicholls State University', 'Thibodaux', 'LA'),
('Northern Arizona University', 'Flagstaff', 'AZ'),
('Northern Illinois University', 'DeKalb', 'IL'),
('Northern Michigan University', 'Marquette', 'MI'),
('Ohio Dominican University', 'Columbus', 'OH'),
('Plymouth State University', 'Plymouth', 'NH'),
('Providence College', 'Providence', 'RI'),
('Quinnipiac University', 'Hamden', 'CT'),
('Radford University', 'Radford', 'VA'),
('Rowan University', 'Glassboro', 'NJ'),
('Sacred Heart University', 'Fairfield', 'CT'),
('Sam Houston State University', 'Huntsville', 'TX'),
('Samford University', 'Birmingham', 'AL'),
('Seton Hall University', 'South Orange', 'NJ'),
('Shippensburg University', 'Shippensburg', 'PA'),
('Siena College', 'Loudonville', 'NY'),
('Slippery Rock University', 'Slippery Rock', 'PA'),
('Southeast Missouri State University', 'Cape Girardeau', 'MO'),
('Southeastern Louisiana University', 'Hammond', 'LA'),
('Southern Connecticut State University', 'New Haven', 'CT'),
('Southern Utah University', 'Cedar City', 'UT'),
('Southwest Texas State University', 'San Marcos', 'TX'),
('Texas State University', 'San Marcos', 'TX'),
('Towson University', 'Towson', 'MD'),
('Troy University', 'Troy', 'AL'),
('Truman State University', 'Kirksville', 'MO'),
('Tulsa University', 'Tulsa', 'OK'),
('UMass Lowell', 'Lowell', 'MA'),
('UMass Dartmouth', 'Dartmouth', 'MA'),
('University of Akron', 'Akron', 'OH'),
('University of Baltimore', 'Baltimore', 'MD'),
('University of California Merced', 'Merced', 'CA'),
('University of Central Missouri', 'Warrensburg', 'MO'),
('University of Dayton', 'Dayton', 'OH'),
('University of Evansville', 'Evansville', 'IN'),
('University of Hartford', 'West Hartford', 'CT'),
('University of Illinois Springfield', 'Springfield', 'IL'),
('University of Indianapolis', 'Indianapolis', 'IN'),
('University of La Verne', 'La Verne', 'CA'),
('University of Louisiana Monroe', 'Monroe', 'LA'),
('University of Mary', 'Bismarck', 'ND'),
('University of Memphis', 'Memphis', 'TN'),
('University of Mississippi Medical Center', 'Jackson', 'MS'),
('University of Missouri Kansas City', 'Kansas City', 'MO'),
('University of Missouri St. Louis', 'St. Louis', 'MO'),
('University of Montevallo', 'Montevallo', 'AL'),
('University of Nebraska Omaha', 'Omaha', 'NE'),
('University of New Haven', 'West Haven', 'CT'),
('University of New Orleans', 'New Orleans', 'LA'),
('University of North Texas', 'Denton', 'TX'),
('University of Northern Colorado', 'Greeley', 'CO'),
('University of Northern Iowa', 'Cedar Falls', 'IA'),
('University of Saint Thomas', 'St. Paul', 'MN'),
('University of San Diego', 'San Diego', 'CA'),
('University of San Francisco', 'San Francisco', 'CA'),
('University of Scranton', 'Scranton', 'PA'),
('University of Sioux Falls', 'Sioux Falls', 'SD'),
('University of South Alabama', 'Mobile', 'AL'),
('University of Tampa', 'Tampa', 'FL'),
('University of the District of Columbia', 'Washington', 'DC'),
('University of the Pacific', 'Stockton', 'CA'),
('University of Toledo', 'Toledo', 'OH'),
('University of Tulsa', 'Tulsa', 'OK'),
('University of West Alabama', 'Livingston', 'AL'),
('University of West Florida', 'Pensacola', 'FL'),
('University of West Georgia', 'Carrollton', 'GA'),
('Utah Valley University', 'Orem', 'UT'),
('Valdosta State University', 'Valdosta', 'GA'),
('West Texas A&M University', 'Canyon', 'TX'),
('Western Illinois University', 'Macomb', 'IL'),
('Western Kentucky University', 'Bowling Green', 'KY'),
('Western Michigan University', 'Kalamazoo', 'MI'),
('Western Oregon University', 'Monmouth', 'OR'),
('Western Washington University', 'Bellingham', 'WA'),
('Wichita State University', 'Wichita', 'KS'),
('Winona State University', 'Winona', 'MN'),
('Youngstown State University', 'Youngstown', 'OH'),

-- ── Faith-based universities ──────────────────────────────────────────────────
('Abilene Christian University', 'Abilene', 'TX'),
('Ave Maria University', 'Ave Maria', 'FL'),
('Azusa Pacific University', 'Azusa', 'CA'),
('Baylor University', 'Waco', 'TX'),
('Belmont University', 'Nashville', 'TN'),
('Biola University', 'La Mirada', 'CA'),
('Butler University', 'Indianapolis', 'IN'),
('Calvin University', 'Grand Rapids', 'MI'),
('Campbell University', 'Buies Creek', 'NC'),
('Creighton University', 'Omaha', 'NE'),
('Dallas Baptist University', 'Dallas', 'TX'),
('Eastern Nazarene College', 'Quincy', 'MA'),
('Franciscan University of Steubenville', 'Steubenville', 'OH'),
('Gonzaga University', 'Spokane', 'WA'),
('Hope College', 'Holland', 'MI'),
('John Carroll University', 'University Heights', 'OH'),
('Lee University', 'Cleveland', 'TN'),
('Lipscomb University', 'Nashville', 'TN'),
('Loyola Marymount University', 'Los Angeles', 'CA'),
('Loyola University Maryland', 'Baltimore', 'MD'),
('Loyola University New Orleans', 'New Orleans', 'LA'),
('Messiah University', 'Mechanicsburg', 'PA'),
('Mizzou', 'Columbia', 'MO'),
('Mount St. Mary''s University', 'Emmitsburg', 'MD'),
('Pepperdine University', 'Malibu', 'CA'),
('Point Loma Nazarene University', 'San Diego', 'CA'),
('Regis University', 'Denver', 'CO'),
('Saint Louis University', 'St. Louis', 'MO'),
('Santa Clara University', 'Santa Clara', 'CA'),
('Seattle Pacific University', 'Seattle', 'WA'),
('Seattle University', 'Seattle', 'WA'),
('Spring Arbor University', 'Spring Arbor', 'MI'),
('Taylor University', 'Upland', 'IN'),
('Thomas More University', 'Crestview Hills', 'KY'),
('Trinity University', 'San Antonio', 'TX'),
('United States Air Force Academy', 'Colorado Springs', 'CO'),
('United States Military Academy', 'West Point', 'NY'),
('United States Naval Academy', 'Annapolis', 'MD'),
('United States Coast Guard Academy', 'New London', 'CT'),
('United States Merchant Marine Academy', 'Kings Point', 'NY'),
('Vanguard University', 'Costa Mesa', 'CA'),
('Wheaton College', 'Wheaton', 'IL'),
('Whitworth University', 'Spokane', 'WA'),
('Xavier University', 'Cincinnati', 'OH'),

-- ── Technical and specialty schools ──────────────────────────────────────────
('Colorado School of Mines', 'Golden', 'CO'),
('Georgia Institute of Technology', 'Atlanta', 'GA'),
('Illinois Institute of Technology', 'Chicago', 'IL'),
('Michigan Technological University', 'Houghton', 'MI'),
('Missouri University of Science and Technology', 'Rolla', 'MO'),
('New Mexico Institute of Mining and Technology', 'Socorro', 'NM'),
('New York Institute of Technology', 'Old Westbury', 'NY'),
('Oregon Health & Science University', 'Portland', 'OR'),
('Savannah College of Art and Design', 'Savannah', 'GA'),
('School of Visual Arts', 'New York', 'NY'),
('The New School', 'New York', 'NY'),
('Parsons School of Design', 'New York', 'NY'),
('Fashion Institute of Technology', 'New York', 'NY'),
('Pratt Institute', 'Brooklyn', 'NY'),
('Ringling College of Art and Design', 'Sarasota', 'FL'),
('Rhode Island School of Design', 'Providence', 'RI'),
('Art Center College of Design', 'Pasadena', 'CA'),

-- ── Additional well-known universities ───────────────────────────────────────
('Adelphi University', 'Garden City', 'NY'),
('Alfred University', 'Alfred', 'NY'),
('Anna Maria College', 'Paxton', 'MA'),
('Arcadia University', 'Glenside', 'PA'),
('Arkansas State University', 'Jonesboro', 'AR'),
('Assumption University', 'Worcester', 'MA'),
('Augustana College', 'Rock Island', 'IL'),
('Augustana University', 'Sioux Falls', 'SD'),
('Aurora University', 'Aurora', 'IL'),
('Baker University', 'Baldwin City', 'KS'),
('Ball State University', 'Muncie', 'IN'),
('Barry University', 'Miami Shores', 'FL'),
('Baruch College', 'New York', 'NY'),
('Benedictine University', 'Lisle', 'IL'),
('Bloomsburg University of Pennsylvania', 'Bloomsburg', 'PA'),
('Bridgewater State University', 'Bridgewater', 'MA'),
('Bryant University', 'Smithfield', 'RI'),
('Bucknell University', 'Lewisburg', 'PA'),
('Buffalo State University', 'Buffalo', 'NY'),
('Cal State Fresno', 'Fresno', 'CA'),
('Cal State Monterey Bay', 'Seaside', 'CA'),
('California Baptist University', 'Riverside', 'CA'),
('California Lutheran University', 'Thousand Oaks', 'CA'),
('Cedarville University', 'Cedarville', 'OH'),
('Champlain College', 'Burlington', 'VT'),
('Chapman University', 'Orange', 'CA'),
('Chatham University', 'Pittsburgh', 'PA'),
('City College of New York', 'New York', 'NY'),
('Clarion University', 'Clarion', 'PA'),
('College of Charleston', 'Charleston', 'SC'),
('College of Holy Cross', 'Worcester', 'MA'),
('College of New Jersey', 'Ewing', 'NJ'),
('College of Saint Benedict', 'St. Joseph', 'MN'),
('College of the Holy Cross', 'Worcester', 'MA'),
('College of William & Mary', 'Williamsburg', 'VA'),
('Concordia University', 'Irvine', 'CA'),
('Coppin State University', 'Baltimore', 'MD'),
('CUNY Brooklyn College', 'Brooklyn', 'NY'),
('CUNY Hunter College', 'New York', 'NY'),
('CUNY Queens College', 'Flushing', 'NY'),
('Dominican University', 'River Forest', 'IL'),
('Drake University', 'Des Moines', 'IA'),
('Drew University', 'Madison', 'NJ'),
('Duquesne University', 'Pittsburgh', 'PA'),
('East Tennessee State University', 'Johnson City', 'TN'),
('Fairleigh Dickinson University', 'Teaneck', 'NJ'),
('Ferris State University', 'Big Rapids', 'MI'),
('Flagler College', 'St. Augustine', 'FL'),
('Florida Gulf Coast University', 'Fort Myers', 'FL'),
('Framingham State University', 'Framingham', 'MA'),
('Franklin & Marshall College', 'Lancaster', 'PA'),
('Fresno Pacific University', 'Fresno', 'CA'),
('Frostburg State University', 'Frostburg', 'MD'),
('Gettysburg College', 'Gettysburg', 'PA'),
('Grace College', 'Winona Lake', 'IN'),
('Hamline University', 'St. Paul', 'MN'),
('Hawaii Pacific University', 'Honolulu', 'HI'),
('High Point University', 'High Point', 'NC'),
('Hofstra University', 'Hempstead', 'NY'),
('Humboldt State University', 'Arcata', 'CA'),
('Hunter College', 'New York', 'NY'),
('Idaho State University', 'Pocatello', 'ID'),
('Immaculata University', 'Immaculata', 'PA'),
('Iona University', 'New Rochelle', 'NY'),
('Jacksonville University', 'Jacksonville', 'FL'),
('John Jay College of Criminal Justice', 'New York', 'NY'),
('Juniata College', 'Huntingdon', 'PA'),
('Kean University', 'Union', 'NJ'),
('Keene State College', 'Keene', 'NH'),
('La Salle University', 'Philadelphia', 'PA'),
('Lafayette College', 'Easton', 'PA'),
('Lake Forest College', 'Lake Forest', 'IL'),
('Linfield University', 'McMinnville', 'OR'),
('Lock Haven University', 'Lock Haven', 'PA'),
('Loyola University Maryland', 'Baltimore', 'MD'),
('Manhattan College', 'Riverdale', 'NY'),
('Marietta College', 'Marietta', 'OH'),
('Marymount Manhattan College', 'New York', 'NY'),
('Massachusetts College of Liberal Arts', 'North Adams', 'MA'),
('McDaniel College', 'Westminster', 'MD'),
('Millersville University', 'Millersville', 'PA'),
('Mills College', 'Oakland', 'CA'),
('Molloy University', 'Rockville Centre', 'NY'),
('Monmouth University', 'West Long Branch', 'NJ'),
('Montana Tech', 'Butte', 'MT'),
('Mount Holyoke College', 'South Hadley', 'MA'),
('Muhlenberg College', 'Allentown', 'PA')

ON CONFLICT (name) DO NOTHING;
